version: 2

models:
  - name: int_amazon_fred_enriched
    description: >
      Combines Amazon purchase and survey data with state-level unemployment and
      national macroeconomic indicators from FRED, enabling state-by-state and
      time-based analysis of consumer behavior.

    columns:
      - name: user_id
        description: "Unique customer ID from Amazon survey and purchase data."
        tests:
          - not_null

      - name: order_date
        description: "Date of purchase."
        tests:
          - not_null

      - name: state
        description: "US state of shipping address."
        tests:
          - not_null

      - name: unemployment_rate
        description: "Monthly unemployment rate for the corresponding state."
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: "{{ unemployment_rate }} between 0 and 50"

      - name: cpi_all_items
        description: "CPI index at the time of purchase."
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: "{{ cpi_all_items }} > 0"
