{% macro rename_state_to_abb(state_name) %}
    case
        when lower({{ state_name }}) = 'alabama' then 'AL'
        when lower({{ state_name }}) = 'alaska' then 'AK'
        when lower({{ state_name }}) = 'arizona' then 'AZ'
        when lower({{ state_name }}) = 'arkansas' then 'AR'
        when lower({{ state_name }}) = 'california' then 'CA'
        when lower({{ state_name }}) = 'colorado' then 'CO'
        when lower({{ state_name }}) = 'connecticut' then 'CT'
        when lower({{ state_name }}) = 'delaware' then 'DE'
        when lower({{ state_name }}) = 'florida' then 'FL'
        when lower({{ state_name }}) = 'georgia' then 'GA'
        when lower({{ state_name }}) = 'hawaii' then 'HI'
        when lower({{ state_name }}) = 'idaho' then 'ID'
        when lower({{ state_name }}) = 'illinois' then 'IL'
        when lower({{ state_name }}) = 'indiana' then 'IN'
        when lower({{ state_name }}) = 'iowa' then 'IA'
        when lower({{ state_name }}) = 'kansas' then 'KS'
        when lower({{ state_name }}) = 'kentucky' then 'KY'
        when lower({{ state_name }}) = 'louisiana' then 'LA'
        when lower({{ state_name }}) = 'maine' then 'ME'
        when lower({{ state_name }}) = 'maryland' then 'MD'
        when lower({{ state_name }}) = 'massachusetts' then 'MA'
        when lower({{ state_name }}) = 'michigan' then 'MI'
        when lower({{ state_name }}) = 'minnesota' then 'MN'
        when lower({{ state_name }}) = 'mississippi' then 'MS'
        when lower({{ state_name }}) = 'missouri' then 'MO'
        when lower({{ state_name }}) = 'montana' then 'MT'
        when lower({{ state_name }}) = 'nebraska' then 'NE'
        when lower({{ state_name }}) = 'nevada' then 'NV'
        when lower({{ state_name }}) = 'new hampshire' then 'NH'
        when lower({{ state_name }}) = 'new jersey' then 'NJ'
        when lower({{ state_name }}) = 'new mexico' then 'NM'
        when lower({{ state_name }}) = 'new york' then 'NY'
        when lower({{ state_name }}) = 'north carolina' then 'NC'
        when lower({{ state_name }}) = 'north dakota' then 'ND'
        when lower({{ state_name }}) = 'ohio' then 'OH'
        when lower({{ state_name }}) = 'oklahoma' then 'OK'
        when lower({{ state_name }}) = 'oregon' then 'OR'
        when lower({{ state_name }}) = 'pennsylvania' then 'PA'
        when lower({{ state_name }}) = 'rhode island' then 'RI'
        when lower({{ state_name }}) = 'south carolina' then 'SC'
        when lower({{ state_name }}) = 'south dakota' then 'SD'
        when lower({{ state_name }}) = 'tennessee' then 'TN'
        when lower({{ state_name }}) = 'texas' then 'TX'
        when lower({{ state_name }}) = 'utah' then 'UT'
        when lower({{ state_name }}) = 'vermont' then 'VT'
        when lower({{ state_name }}) = 'virginia' then 'VA'
        when lower({{ state_name }}) = 'washington' then 'WA'
        when lower({{ state_name }}) = 'west virginia' then 'WV'
        when lower({{ state_name }}) = 'wisconsin' then 'WI'
        when lower({{ state_name }}) = 'wyoming' then 'WY'
        else null
    end
{% endmacro %}
